In [33]:
# !conda install pandas
#KERAS
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.optimizers import SGD,RMSprop,adam
from keras.utils import np_utils
# from array import array

import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import os
import theano
from PIL import Image
from numpy import *
# SKLEARN
from sklearn.utils import shuffle
from sklearn.cross_validation import train_test_split

In [34]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Conv3D, MaxPooling3D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras import backend as K
from keras.preprocessing.image import img_to_array, load_img
import numpy as np

In [35]:
# input image dimensions
img_rows, img_cols = 128, 128
# number of channels
img_channels = 1

# data
path1 = 'C:/Users/Java/Desktop/Project/Project_Image/data8/train'    
#path of folder of images    
path2 = 'C:/Users/Java/Desktop/Project/Project_Image/data8/train_set'  
#path of folder to save images    

listing = os.listdir(path1) 
num_samples=size(listing)
print(num_samples)


13668


In [36]:
for file in listing:
    im = Image.open(path1 + '/' + file)   
    img = im.resize((img_rows,img_cols))
    gray = img.convert('RGBA')
                #need to do some more processing here           
#     img.save(path2 +'/' +  file, "JPEG")
    gray.save(path2 +'\\' +  file, "JPEG")

imlist = os.listdir(path2)



In [37]:
im1 = array(Image.open(path2 + '/'+ imlist[0])) # open one image to get size
m,n = im1.shape[0:2] # get the size of the images
imnbr = len(imlist) # get the number of images

In [38]:
# create matrix to store all flattened images
immatrix = array([array(Image.open(path2+ '/' +im2)).flatten()
              for im2 in imlist],'f')
                



In [39]:
label=np.ones((num_samples,),dtype = int)
# np.ones(shape[, dtype, order])
# 依据给定形状和类型(shape[, dtype, order])返回一个新的元素全部为1的数组

label[0:945]=0
label[946:2195]=1
label[2196:4826]=2
label[4827:6919]=3
label[6920:7466]=4
label[7467:9157]=5
label[9158:11424]=6
label[11425:12007]=7
label[12008:13667]=8

# 0 二條城1-100		1-746
# 1 三十三間堂101-200	747-1796
# 2 千本鳥居201-300	1797-4228
# 3 平等院鳳凰堂301-400	4229-6120
# 4 京都御所401-500	6121-6468
# 5 京都塔501-600		6469-7959
# 6 金格寺601-700		7960-10028
# 7 清水寺701-800		10029-10411
# 8 渡月橋801-900		10412-11872

data,Label = shuffle(immatrix,label, random_state=3)
train_data = [data,Label]

img=immatrix[200].reshape(img_rows,img_cols,3)
plt.imshow(img)
# plt.imshow(img,cmap='gray') 
# cmap: 颜色图谱（colormap), 默认绘制为RGB(A)颜色空间。
print (train_data[0].shape)
print (train_data[1].shape)

(13668, 49152)
(13668,)


In [40]:
#batch_size to train
batch_size = 50
# number of output classes
nb_classes = 9
# number of epochs to train
nb_epoch = 20

# number of convolutional filters to use
nb_filters = 32
# size of pooling area for max pooling
nb_pool = 2
# convolution kernel size
nb_conv = 3

#%%
(X, y) = (train_data[0],train_data[1]) #？？

In [41]:
# STEP 1: split X and y into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=4)


X_train = X_train.reshape(X_train.shape[0],img_rows, img_cols,3)
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols,3)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

X_train /= 255
X_test /= 255

print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

X_train shape: (12301, 128, 128, 3)
12301 train samples
1367 test samples


In [42]:
# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

i = 800
plt.imshow(X_train[i, 0], interpolation='nearest')
print("label : ", Y_train[i,:])

label :  [ 0.  0.  0.  0.  0.  0.  1.  0.  0.]


In [62]:
model = Sequential()
# 加入卷積層1
model.add(Conv2D(filters=32, kernel_size = (2,2),   # 32個3*3濾鏡
                 input_shape = (128,128,3),   # 圖片大小&三原色
                 activation = 'relu',
                 padding = 'same' # 經過此層影像大小不變
                 ) 
         )


# 控制overfit
model.add(Dropout(rate=0.25))    


# 加入池化層1
model.add(MaxPooling2D(pool_size=(2,2))) 

##################################################################

# 加入卷積層2
model.add(Conv2D(filters=64, kernel_size = (2,2),   # 64個3*3濾鏡
                 activation = 'relu',
                 padding = 'same' # 經過此層影像大小不變
                 ) 
         )


# 控制overfit
model.add(Dropout(rate=0.25))          



# 加入池化層2
model.add(MaxPooling2D(pool_size=(2,2))) 

##################################################################

# 加入卷積層3
model.add(Conv2D(filters=128, kernel_size = (2,2),   # 64個3*3濾鏡
                 activation = 'relu',
                 padding = 'same' # 經過此層影像大小不變
                 ) 
         )


# 控制overfit
model.add(Dropout(rate=0.25))          



# 加入池化層2
model.add(MaxPooling2D(pool_size=(2,2))) 

##################################################################

# 加入平坦層
model.add(Flatten()) #28*28*64


# 控制overfit
model.add(Dropout(rate=0.25))    


##################################################################

# 加入隱藏層
model.add(Dense(1000, activation = 'relu'))


# 控制overfit
model.add(Dropout(rate=0.25))    

##################################################################
 # 加入隱藏層
model.add(Dense(500, activation = 'relu'))


# 控制overfit
model.add(Dropout(rate=0.25))    

##################################################################

# 建立輸出層
model.add(Dense(9, activation = 'softmax'))

##################################################################

# 查看模型摘要
print(model.summary())

##################################################################

###############################
#                             #
#          準備訓練            #
#                             #
###############################
model.compile(loss = 'categorical_crossentropy',  # 損失函數
              optimizer = 'adam',                 # 最優化方法
              metrics = ['accuracy'])             # 以準確率評估

#%%

hist = model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
              verbose=1, validation_data=(X_test, Y_test))
            
            
# hist = model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
#               verbose=1, validation_split=0.2)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_25 (Conv2D)           (None, 128, 128, 32)      416       
_________________________________________________________________
dropout_31 (Dropout)         (None, 128, 128, 32)      0         
_________________________________________________________________
max_pooling2d_16 (MaxPooling (None, 64, 64, 32)        0         
_________________________________________________________________
conv2d_26 (Conv2D)           (None, 64, 64, 64)        8256      
_________________________________________________________________
dropout_32 (Dropout)         (None, 64, 64, 64)        0         
_________________________________________________________________
max_pooling2d_17 (MaxPooling (None, 32, 32, 64)        0         
_________________________________________________________________
conv2d_27 (Conv2D)           (None, 32, 32, 128)       32896     
__________

C:\Users\Java\Anaconda3\envs\tensorflow\lib\site-packages\keras\models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 12301 samples, validate on 1367 samples
Epoch 1/20
12301/12301 [==============================] - 456s - loss: 1.5171 - acc: 0.5145 - val_loss: 1.3409 - val_acc: 0.5530
Epoch 2/20
12301/12301 [==============================] - 436s - loss: 1.0605 - acc: 0.6397 - val_loss: 1.1170 - val_acc: 0.6496
Epoch 3/20
12301/12301 [==============================] - 440s - loss: 0.9114 - acc: 0.6867 - val_loss: 1.0089 - val_acc: 0.6803
Epoch 4/20
12301/12301 [==============================] - 436s - loss: 0.7764 - acc: 0.7308 - val_loss: 0.9485 - val_acc: 0.7030
Epoch 5/20
12301/12301 [==============================] - 434s - loss: 0.6526 - acc: 0.7712 - val_loss: 0.9451 - val_acc: 0.6840
Epoch 6/20
12301/12301 [==============================] - 432s - loss: 0.5348 - acc: 0.8096 - val_loss: 0.9281 - val_acc: 0.6796
Epoch 7/20
12301/12301 [==============================] - 433s - loss: 0.4195 - acc: 0.8501 - val_loss: 0.9665 - val_acc: 0.6854
Epoch 8/20
12301/12301 [========================

KeyboardInterrupt: 

In [63]:
from sklearn.metrics import classification_report,confusion_matrix

In [64]:
# Y_pred = model.predict(X_test)
# print(Y_pred)
# y_pred = np.argmax(Y_pred, axis=1)
# print(y_pred)
y_pred = model.predict_classes(X_test)
print(y_pred)

p=model.predict_proba(X_test) # to predict probability

target_names = ['class 0(二條城)', 'class 1(三十三間堂)', 'class 2(千本鳥居)','class 3(平等院鳳凰堂)','class 4(京都御所)','class 5(京都塔)','class 6(金閣寺)','class 7(清水寺)','class 8(渡月橋)']
print(classification_report(np.argmax(Y_test,axis=1), y_pred,target_names=target_names))
print(confusion_matrix(np.argmax(Y_test,axis=1), y_pred))

1367/1367 [==============================] - 7s     
[3 8 6 ..., 3 8 3]
1367/1367 [==============================] - 7s     
                 precision    recall  f1-score   support

   class 0(二條城)       0.56      0.44      0.49       103
 class 1(三十三間堂)       0.48      0.53      0.50       122
  class 2(千本鳥居)       0.77      0.67      0.72       245
class 3(平等院鳳凰堂)       0.75      0.83      0.79       218
  class 4(京都御所)       0.36      0.20      0.26        50
   class 5(京都塔)       0.79      0.76      0.77       169
   class 6(金閣寺)       0.74      0.90      0.81       248
   class 7(清水寺)       0.31      0.18      0.23        55
   class 8(渡月橋)       0.72      0.78      0.75       157

    avg / total       0.68      0.70      0.68      1367

[[ 45  42   3   2   0   4   6   1   0]
 [ 20  65   6   0   1  10  14   1   5]
 [  5  10 165  42   2   5  16   0   0]
 [  0   4  22 182   2   1   7   0   0]
 [  1   1   3  15  10   9   8   1   2]
 [  4   5   6   0  11 129  10   1   3]
 [  4   4  

In [61]:
y_pred = model.predict_classes(X_test)
print(y_pred)

p=model.predict_proba(X_test) # to predict probability

target_names = ['class 0(二條城)', 'class 1(三十三間堂)', 'class 2(千本鳥居)','class 3(平等院鳳凰堂)','class 4(京都御所)','class 5(京都塔)','class 6(金閣寺)','class 7(清水寺)','class 8(渡月橋)']
print(classification_report(np.argmax(Y_test,axis=1), y_pred,target_names=target_names))
print(confusion_matrix(np.argmax(Y_test,axis=1), y_pred))

1367/1367 [==============================] - 11s    
[3 8 6 ..., 3 8 3]
1367/1367 [==============================] - 11s    
                 precision    recall  f1-score   support

   class 0(二條城)       0.54      0.57      0.55       103
 class 1(三十三間堂)       0.51      0.39      0.44       122
  class 2(千本鳥居)       0.78      0.62      0.69       245
class 3(平等院鳳凰堂)       0.68      0.98      0.81       218
  class 4(京都御所)       0.42      0.20      0.27        50
   class 5(京都塔)       0.74      0.74      0.74       169
   class 6(金閣寺)       0.76      0.79      0.78       248
   class 7(清水寺)       0.48      0.20      0.28        55
   class 8(渡月橋)       0.72      0.83      0.77       157

    avg / total       0.68      0.69      0.68      1367

[[ 59  18   9   4   0   6   4   2   1]
 [ 28  48  13   2   0  12  16   1   2]
 [  7   8 152  56   0   6  13   0   3]
 [  1   1   2 213   0   1   0   0   0]
 [  2   2   0  20  10   7   5   1   3]
 [  6   6   1   5  11 125  13   1   1]
 [  4   8  

In [54]:
show_train_history(hist,'acc','val_acc')

NameError: name 'hist' is not defined